<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="iotbuilding" nsURI="http://example.org/iotbuilding/1.0" nsPrefix="iotbuilding">
  <eClassifiers xsi:type="ecore:EEnum" name="FloorState">
    <eLiterals name="Normal"/>
    <eLiterals name="FireSmoke" value="1"/>
    <eLiterals name="HVACFault" value="2"/>
    <eLiterals name="OccupancySurge" value="3"/>
    <eLiterals name="SpoofingAttack" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RoomType">
    <eLiterals name="Office"/>
    <eLiterals name="Corridor" value="1"/>
    <eLiterals name="Server" value="2"/>
    <eLiterals name="Kitchen" value="3"/>
    <eLiterals name="Lobby" value="4"/>
    <eLiterals name="Stairwell" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SensorModality">
    <eLiterals name="Temperature"/>
    <eLiterals name="CO2" value="1"/>
    <eLiterals name="Humidity" value="2"/>
    <eLiterals name="Motion" value="3"/>
    <eLiterals name="Power" value="4"/>
    <eLiterals name="Smoke" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConnRelation">
    <eLiterals name="ADJACENT_DOOR"/>
    <eLiterals name="SHARED_WALL" value="1"/>
    <eLiterals name="SAME_HVAC_DUCT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BuildingSnapshot">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="#//FloorState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="windowStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="floorId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rooms" upperBound="-1"
        eType="#//Room" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensor" upperBound="-1"
        eType="#//Sensor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Room">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roomType" eType="#//RoomType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="floorArea" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nominalOccupancy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connection" upperBound="-1"
        eType="#//Connection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="room_connection" upperBound="-1"
        eType="#//Connection" eOpposite="#//Connection/room"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="has" upperBound="-1" eType="#//Sensor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modality" eType="#//SensorModality"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mean" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="slope" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zScoreVsHistory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relation" eType="#//ConnRelation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="airflowCoupling" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="room" lowerBound="1" eType="#//Room"
        eOpposite="#//Room/room_connection"/>
  </eClassifiers>
</ecore:EPackage>
